#!/bin/sh

# The MIT License (MIT)
#
# Copyright (c) 2016 Peter Kenji Yamanaka
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# pstate-frequency
# by: pyamsoft <pyam(dot)soft(at)gmail(dot)com>
readonly version="3.0.0"

# Exit codes
# 0 - Success
# 1 - Missing Binary
# 2 - Invalid option
# 3 - Wrong operation mode

# Options that do not handle an argument
display_help=0
display_version=0

execution_delay=0 # Number of seconds to delay script
execution_sleep=0 # Number of seconds to sleep in between setting values

# Options that expect an argument

# Log levels
readonly const_log_level_off=0
readonly const_log_level_quiet=1
readonly const_log_level_normal=2
readonly const_log_level_verbose=3
readonly const_log_level_all=4
log_level="${const_log_level_normal}"

# Execution modes
readonly const_mode_help=0
readonly const_mode_version=1
readonly const_mode_get=2
readonly const_mode_set=3
mode="${const_mode_help}"

# Get modes
readonly const_get_type_current=0
readonly const_get_type_real=1
get_type="${const_get_type_current}"

# Set commands
readonly const_set_max_false=0
readonly const_set_max_true=1
set_max_type="${const_set_max_false}"
set_max_arg=""

readonly const_set_min_false=0
readonly const_set_min_true=1
set_min_type="${const_set_min_false}"
set_min_arg=""

readonly const_set_turbo_false=0
readonly const_set_turbo_true=1
set_turbo_type="${const_set_turbo_false}"
set_turbo_arg=""

readonly const_set_governor_false=0
readonly const_set_governor_true=1
set_governor_type="${const_set_governor_false}"
set_governor_arg=""

# Plan modes
readonly const_power_plan_none=0
readonly const_power_plan_powersave=1
readonly const_power_plan_balanced=2
readonly const_power_plan_performance=3
power_plan_mode="${const_power_plan_none}"

# Supported option flags
#
# -H | --help
# -V | --version
# -G | --get
# -S | --set
#
# -p | --plan
# -m | --max
# -n | --min
# -t | --turbo
# -g | --governor
#
# -c | --current
# -r | --real
#
# -d | --debug
# -q | --quiet
#
# --delay
# --color
# --sleep

# Normal log
# Can be seen at
# log_level = normal, verbose, all
log()
{
  if [ "${log_level}" -ge "${const_log_level_normal}" ]; then
    printf -- "$@\n"
  fi
}

# Verbose log
# Can be seen at
# log_level = verbose, all
log_verbose()
{
  if [ "${log_level}" -ge "${const_log_level_verbose}" ]; then
    printf -- "DEBUG: $@\n"
  fi
}

# All log
# Can be seen at
# log_level = all
log_all()
{
  if [ "${log_level}" -eq "${const_log_level_all}" ]; then
    printf -- "VERBOSE: $@\n"
  fi
}

# Quiet log
# Can be seen at
# log_level = quiet, normal, verbose, all
log_quiet()
{
  if [ "${log_level}" -ge "${const_log_level_quiet}" ]; then
    printf -- "$@\n"
  fi
}

# Error logging
elog()
{
  log "ERROR :$@" 1>&2
}

# Verbose error logging
elog_verbose()
{
  log_verbose "ERROR: $@" 1>&2
}

# All error logging
elog_all()
{
  log_all "ERROR: $@" 1>&2
}

# Quiet error logging
elog_quiet()
{
  log_quiet "ERROR: $@" 1>&2
}

# Check the environment path for the given binary, exit if it is not found
check_binary()
{
  if ! which "$1" > /dev/null 2>&1; then
    log_quiet "The '$1' binary is required for operation of this script."
    log_quiet "Please install '$1' onto your system."
    exit 1
  fi
}

# Print usage
print_usage()
{
  log "usage:"
  log "pstate-frequency [verbose] [ACTION] [option(s)]"
  log
  log "verbose:"
  log "    unprivileged:"
  log "    -d | --debug     Print debugging messages to stdout (multiple)"
  log "    -q | --quiet     Supress all non-error output (multiple)"
  log "    --color          Colorize output"
  log
  log
  log "actions:"
  log "    unprivileged:"
  log "    -H | --help      Display this help and exit"
  log "    -V | --version   Display application version and exit"
  log "    -G | --get       Access current CPU values"
  log "    --delay          Delay execution by 5 seconds"
  log "    privileged:"
  log "    -S | --set       Modify current CPU values"
  log
  log
  log "options:"
  log "    unprivileged:"
  log "    -c | --current   Display the current user set CPU values"
  log "    -r | --real      Display the real time CPU frequencies"
  log "    privileged:"
  log "    -p | --plan      Set a predefined power plan"
  log "    -m | --max       Modify current CPU max frequency"
  log "    -g | --governor  Set the cpufreq governor"
  log "    -n | --min       Modify current CPU min frequency"
  log "    -t | --turbo     Modify curent CPU turbo boost state"
  log "    --sleep          Sleep before setting CPU frequencies"
}

# Check if the passed in variable is digits
is_digits()
{
  case "$1" in
    ([!0-9]*|'')
      printf -- 0
      ;;
    (*)
      printf -- 1
      ;;
  esac
}

# Print version
print_version()
{
  log_quiet "pstate-frequency version ${version}"
}

# Increase log verbosity
log_more_verbose()
{
  if [ "${log_level}" -lt "${const_log_level_all}" ]; then
    log_level=$((${log_level} + 1))
    log_all "log_level more verbose"
  fi
}

# Decrease log verbosity
log_less_verbose()
{
  if [ "${log_level}" -gt "${const_log_level_off}" ]; then
    log_all "log_level less verbose"
    log_level=$((${log_level} - 1))
  fi
}

# Set the argument for cpu_max
# Can be set multiple times, final time overrides
set_max()
{
  log_verbose "set_max requires SET operation mode"
  if [ "${mode}" -eq "${const_mode_set}" ]; then
    local value=""
    log_verbose "Check for special case arguments: max, min"
    if [ "$1" = "max" ]; then
      log_verbose "Argument was 'max' set to 100"
      value="100"
    elif [ "$1" = "min" ]; then
      log_verbose "Argument was 'min' set to 0"
      value="0"
    else
      log_verbose "Argument was not special, read as is"
      value="$1"
    fi
    log_verbose "Check that '${value}' is all digits"
    if [ $(is_digits "${value}") -eq 1 ]; then
      log_verbose "'${value}' is all digits"
      set_max_type="${const_set_max_true}"
      set_max_arg="${value}"
    else
      elog_quiet "max argument '${value}' is not a number"
      unset value
      exit 2
    fi
    unset value
  else
    elog_quiet "Cannot set max outside of SET operation mode"
    exit 3
  fi
}

# Handle long options which take arguments
handle_long_option_argument()
{
  if [ "$1" = '-' ]; then
    log_all "Skip '-' processing"
  elif [ -z "${option_expects_argument}" ]; then
    elog_verbose "option does not expect argument!"
    elog_verbose "argument: $1"
    elog_quiet "Illegal argument $1"
    exit 2
  else
    log_verbose "option expects argument: ${option_expects_argument}"
    log_verbose "argument: $1"

    case "${option_expects_argument}" in
      plan)
        log_verbose "Long option: plan"
        ;;
      max)
        log_verbose "Long option: max"
        set_max "$1"
        ;;
      min)
        log_verbose "Long option: min"
        ;;
      turbo)
        log_verbose "Long option: turbo"
        ;;
      governor)
        log_verbose "Long option: governor"
        ;;
      *)
        elog_quiet "Invalid option --${option_expects_argument}"
        exit 2
        ;;
    esac
  fi
}


# While risky to call eval, this is one way to
# emulate the bash indirect_expansion ability
long_option=""
option_expects_argument=""
eval optind_expanded="\$${OPTIND}"
while [ -n "${optind_expanded}" ]; do
  while getopts ":HVGSp:m:n:t:g:crdq-:" option; do

    # Log if not long option
    if [ "${option}" != '-' ]; then
      log_verbose "parse short option: -${option} ${OPTARG}"
    fi

    # Set only on long option with arg
    if [ -n "${option_expects_argument}" ]; then
      elog_quiet "Long option --${long_option} expects argument"
      exit 2
    fi

    option_expects_argument=""
    long_option="${option_expects_argument}"
    case "${option}" in
      -)
        log_verbose "parse long option: -${option}${OPTARG}"
        case "${OPTARG}" in
          help)
            print_usage
            exit 0
            ;;
          version)
            print_version
            exit 0
            ;;
          get)
            mode="${const_mode_get}"
            ;;
          set)
            mode="${const_mode_set}"
            ;;
          plan)
            option_expects_argument="plan"
            long_option="${option_expects_argument}"
            ;;
          max)
            option_expects_argument="max"
            long_option="${option_expects_argument}"
            ;;
          min)
            option_expects_argument="min"
            long_option="${option_expects_argument}"
            ;;
          turbo)
            option_expects_argument="turbo"
            long_option="${option_expects_argument}"
            ;;
          governor)
            option_expects_argument="governor"
            long_option="${option_expects_argument}"
            ;;
          current)
            ;;
          real)
            ;;
          debug)
            log_more_verbose
            ;;
          quiet)
            log_less_verbose
            ;;
          delay)
            ;;
          color)
            ;;
          sleep)
            ;;
          *)
            # We must provide our own error message in this case
            elog_quiet "Illegal option --${OPTARG}"
            print_usage
            exit 2
            ;;
        esac
        ;;
      H)
        print_usage
        exit 0
        ;;
      V)
        print_version
        exit 0
        ;;
      G)
        ;;
      S)
        mode="${const_mode_set}"
        ;;
      p)
        ;;
      m)
        set_max "${OPTARG}"
        ;;
      n)
        ;;
      t)
        ;;
      g)
        ;;
      c)
        ;;
      r)
        ;;
      d)
        log_more_verbose
        ;;
      q)
        log_less_verbose
        ;;
      *)
        elog_quiet "Illegal option -${OPTARG}"
        print_usage
        exit 2
        ;;
    esac
  done

  # Re-establish the current OPTIND target
  eval optind_expanded="\$${OPTIND}"
  if [ -z "${optind_expanded}" ]; then
    if [ -n "${option_expects_argument}" ]; then
      elog_quiet "Long option --${long_option} expects argument"
      exit 2
    else
      break
    fi
  else
    # This is a plain arg and should be handled by one of the options which takes an argument
    handle_long_option_argument "${optind_expanded}"

    # Set back to null
    option_expects_argument=""
    long_option="${option_expects_argument}"
  fi

  # Shift the options
  shift $OPTIND
  OPTIND=1
done

case "${mode}" in
  "${const_mode_get}")
    ;;
  "${const_mode_set}")
    ;;
esac


# vim: set syntax=sh tabstop=2 softtabstop=2 shiftwidth=2 shiftround expandtab:

