#!/bin/sh

# Clean the build
make clean || exit 1

# Run coverity build tool
current_date=$(date "+%Y-%m-%d %H-%M %Z")
cov-build --dir cov-int make bin || exit 1

# Create a tarball for uploading
mkdir -p coverity
tar czvf "coverity/pstate-frequency-${current_date}.tar.gz" cov-int || exit 1

# Copy created tar to downloads folder for uploading
download_dir=$(xdg-user-dir DOWNLOAD)
cp "coverity/pstate-frequency-${current_date}.tar.gz" "${download_dir}"

# Clean exit
exit 0
