#!/bin/sh

# The GPLv2 License
#
#   Copyright (C) 2025 pyamsoft
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Get the root directory of the project
root_dir="$(dirname "$(realpath "$0")")"
root_dir="$(realpath "${root_dir}/../..")"
readonly root_dir

_get_version() {
  awk -F '=' '{ if (/^readonly __VERSION=/) { print $2 } }' "${root_dir}/pstate-frequency" | tr '"' ' ' | sed 's/[[:space:]]//g'
}

main() {
  _version="$(_get_version)" || return 1

  cd "${root_dir}" || {
    printf -- 'Failed to move into project root_dir: %s\n' "${root_dir}"
    return 1
  }

  # Run from the root dir with the Makefile
  sudo checkinstall \
    --pkgname 'pstate-frequency' \
    --pkgversion "${_version}" \
    --pkgrelease "1" \
    --pkglicense "GPL2" \
    --maintainer "pyamsoft" \
    --provides "pstate-frequency" \
    --requires "coreutils,grep,awk"

  unset _version
  return 0
}

main "$@" || exit 1
exit 0
